# Generated by Django 3.1 on 2020-09-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pub_date',
            new_name='timestamp',
        ),
    ]
