# Generated by Django 3.1 on 2020-09-24 08:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(default=django.contrib.auth.models.User, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
