# Generated by Django 3.1 on 2020-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.DeleteModel(
            name='ReadMessage',
        ),
    ]
