# Generated by Django 3.1 on 2020-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201005_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_message',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
    ]
