# Generated by Django 3.1 on 2020-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200924_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='Нет сообщения', verbose_name='Сообщение'),
        ),
    ]
