# Generated by Django 3.1 on 2020-10-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201008_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_message2',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_message3',
            field=models.FileField(blank=True, null=True, upload_to='message_file'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_message2',
            field=models.ImageField(blank=True, null=True, upload_to='message_image', verbose_name='Изображения в сообщениях'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_message3',
            field=models.ImageField(blank=True, null=True, upload_to='message_image', verbose_name='Изображения в сообщениях'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_message4',
            field=models.ImageField(blank=True, null=True, upload_to='message_image', verbose_name='Изображения в сообщениях'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_message5',
            field=models.ImageField(blank=True, null=True, upload_to='message_image', verbose_name='Изображения в сообщениях'),
        ),
    ]
