# Generated by Django 3.1 on 2020-10-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201008_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat', to='chat.chat', verbose_name='Получатель')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='read_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readInChat', to='chat.readmessage'),
            preserve_default=False,
        ),
    ]
