# Generated by Django 3.1 on 2020-09-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200917_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='slug',
        ),
    ]
