# Generated by Django 3.1 on 2020-09-18 03:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_remove_chat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(default=django.contrib.auth.models.User, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
