# Generated by Django 3.1 on 2020-10-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20201008_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_chat',
        ),
        migrations.DeleteModel(
            name='ReadMessage',
        ),
    ]
