# Generated by Django 3.1 on 2020-09-18 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20200918_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image_chat',
            field=models.ImageField(blank=True, null=True, upload_to='image_chat', verbose_name='Фото беседы'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
