# Generated by Django 3.1 on 2020-10-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20201008_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='read',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='update_read', to='chat.readmessage', verbose_name='Участник'),
            preserve_default=False,
        ),
    ]
