# Generated by Django 3.1 on 2020-10-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20201022_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='read',
        ),
        migrations.DeleteModel(
            name='ReadMessage',
        ),
    ]
