# Generated by Django 3.1 on 2020-10-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20201022_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=30, verbose_name='Id комнаты')),
                ('recipient', models.CharField(max_length=30, verbose_name='id получателей')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
        ),
    ]
