# Generated by Django 2.2.12 on 2020-08-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profil'),
        ),
    ]
