# Generated by Django 2.2.12 on 2020-08-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200828_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='accounts.Post', verbose_name='Профиль пользователя'),
        ),
    ]
