# Generated by Django 3.1 on 2020-09-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Почта', max_length=100, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.EmailField(default='Номер телефона', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
