# Generated by Django 3.1 on 2020-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200901_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-datetime'], 'verbose_name': 'Пользовательская новость', 'verbose_name_plural': 'Пользовательские новости'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default='Номер телефона', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
