# Generated by Django 3.1 on 2020-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200907_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='1@1.11', max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default='+7', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
