# Generated by Django 2.2.12 on 2020-08-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Заголовок статьи', models.CharField(max_length=70)),
                ('Url Адрес', models.SlugField(max_length=150, null=True, unique=True)),
                ('Содержание статьи', models.TextField(max_length=1000)),
                ('Главное изображение', models.ImageField(upload_to='Articles')),
                ('Второе изображение', models.ImageField(upload_to='Articles')),
                ('Третье изображение', models.ImageField(upload_to='Articles')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
