# Generated by Django 2.2.12 on 2020-08-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200820_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Заголовок статьи',
            new_name='title',
        ),
    ]
