# Generated by Django 2.2.12 on 2020-08-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200820_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Содержание статьи',
            new_name='text_article',
        ),
    ]
