# Generated by Django 2.2.12 on 2020-08-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200820_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='Articles', verbose_name='Главное изображение статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_three',
            field=models.ImageField(upload_to='Articles', verbose_name='Дополнительное изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_two',
            field=models.ImageField(upload_to='Articles', verbose_name='Дополнительное изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL адрес статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_article',
            field=models.TextField(max_length=1000, verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название статьи'),
        ),
    ]
