# Generated by Django 2.2.12 on 2020-08-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200825_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_article',
            field=models.TextField(max_length=5000, verbose_name='Содержание статьи'),
        ),
    ]
