# Generated by Django 3.1 on 2020-09-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
